package com.alibaba.cloud.ai.graph.reactive.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serial;
import java.io.Serializable;

/**
 * @author heguangfu
 * @date 2024/8/30 22:17
 **/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ChatUsage implements Serializable {

    @Serial
    private static final long serialVersionUID = -9099360757421058438L;

    /**
     * Number of tokens in the generated completion.
     */
    private int completionTokens;

    /**
     * Number of tokens in the prompt.
     */
    private int promptTokens;

    /**
     * Total number of tokens used in the request (prompt + completion).
     */
    private int totalTokens;
    /**
     * Breakdown of tokens used in a completion.
     */
    private CompletionTokensDetails completionTokensDetails;
    /**
     * Breakdown of tokens used in the prompt.
     */
    private PromptTokensDetails promptTokensDetails;


    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class CompletionTokensDetails {
        /**
         * 使用预测输出时，完成中出现的预测中的标记数。
         */
        private int acceptedPredictionTokens;
        /**
         * 模型生成的音频输入标记。
         */
        private int audioTokens;
        /**
         * Tokens generated by the model for reasoning.
         */
        private int reasoningTokens;
        /**
         * 使用预测输出时，预测中未出现在完成中的标记数。但是，与推理令牌一样，出于计费、输出和上下文窗口限制的目的，这些令牌仍计入总完成令牌中。
         */
        private int rejectedPredictionTokens;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    @JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
    @JsonIgnoreProperties(ignoreUnknown = true)
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public static class PromptTokensDetails {
        /**
         * 模型生成的音频输入标记。
         */
        private int audioTokens;
        /**
         * Cached tokens present in the prompt.
         */
        private int cachedTokens;
    }
}
