package com.alibaba.cloud.ai.graph.reactive.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serial;
import java.io.Serializable;
import java.util.List;

/**
 * @author heguangfu
 * @date 2024/8/30 22:17
 **/
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class ChatMessage implements Serializable {

    @Serial
    private static final long serialVersionUID = -7426787722103783517L;
    /**
     * The text associated with this message payload.
     * The contents of the chunk message.
     */
    private String content;
    /**
     * reasoning_content
     */
    private String reasoningContent;
    /**
     * The tool calls generated by the model, such as function calls.
     */
    private List<ChatToolCall> toolCalls;
    /**
     * The role associated with this message payload.
     */
    private String role;
    /**
     * The refusal message generated by the model.
     */
    private String refusal;

}