package com.alibaba.cloud.ai.graph.reactive.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * @author heguangfu
 * @date 2024/8/28 11:34
 **/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class OpenAiChatMessage {

    /*
     * The text associated with this message payload.
     */
    private String content;
    /**
     * The refusal message generated by the model.
     */
    private String refusal;
    /*
     * The role associated with this message payload.
     */
    private String role;
    /*
     * The name of the author of this message.
     */
    private String name;
    /**
     * The tool calls generated by the model, such as function calls.
     */
    private List<ChatToolCall> toolCalls;
    /**
     * Tool call that this message is responding to.
     */
    private String toolCallId;
    /**
     * Data about a previous audio response from the model.
     * <a href="https://platform.openai.com/docs/guides/audio">Learn more.</a>
     */
    private Audio audio;

}
